In [0]:
import tweepy
import pandas as pd
import json

In [0]:
auth = tweepy.OAuthHandler('','')
auth.set_access_token('','')

In [0]:
api = tweepy.API(auth)

In [0]:
user = api.get_user('MIDASIIITD')

In [5]:
print('User name = ',user.screen_name)
print('no_of_followers = ',user.followers_count)
no_of_status = user.statuses_count
print('no_of_tweets = ',no_of_status)

User name =  midasIIITD
no_of_followers =  265
no_of_tweets =  334

In [0]:
result_set_midas = user.timeline(count = no_of_status,truncated = False)

In [7]:
no_of_tweets_ret = len(result_set_midas)

user.statuses_count,no_of_tweets_ret

(334, 200)

In [0]:
last_id = result_set_midas[-1]._json['id']

In [9]:
result_set_midas_older = user.timeline(max_id = last_id,count = no_of_status-no_of_tweets_ret )
no_of_tweets_ret_older = len(result_set_midas_older)
no_of_tweets_ret_older

134

In [10]:
print(result_set_midas[-1]._json['id'])
print(result_set_midas_older[0]._json['id'])

1059529161444900865
1059529161444900865

In [0]:
data = []
result = result_set_midas+result_set_midas_older
for i in range(no_of_status):
    data.append(result[i]._json)

In [15]:
with open('result.jsonlines','w') as fp:
    json.dump(data, fp)
fp.close

In [0]:
with open('result.jsonlines','r') as fp:
    try:
        data = json.load(fp)
    except:
        print('JSON is not loading')
    fp.close

In [17]:
len(data)

334

In [0]:
coloumn = ['created_at','text','retweet_count','favorite_count','no_of_media']

In [0]:
tweet = [['' for i in range(len(coloumn))] for j in range(no_of_status)]

In [0]:
for i in range(no_of_status):
    for j in range(len(coloumn)-1):
        tweet[i][j] = data[i][coloumn[j]]
    try:
        tweet[i][-1] = len([data[i]['entities']['media']])
    except:
        tweet[i][-1] = 'None'

In [0]:
d = pd.DataFrame(tweet,columns = coloumn)

In [22]:
d

,created_at,text,retweet_count,favorite_count,no_of_media
0,Sun Apr 07 11:43:24 +0000 2019,We request all students whose interview are sc...,1,0,None
1,Sun Apr 07 06:55:19 +0000 2019,"Other queries: ""none of the Tweeter Apis give ...",2,3,None
2,Sun Apr 07 06:53:38 +0000 2019,"Other queries: ""do we have to make two differe...",1,4,None
3,Sun Apr 07 05:32:27 +0000 2019,"Other queries: ""If using Twitter api, it does ...",1,4,None
4,Sun Apr 07 05:29:40 +0000 2019,Response to some queries asked by students on ...,1,6,None
5,Sat Apr 06 17:11:29 +0000 2019,RT @kdnuggets: Top 8 #Free Must-Read #Books on...,2,0,None
6,Sat Apr 06 16:43:27 +0000 2019,@nupur_baghel @PennDATS Congratulation @nupur_...,3,15,None
7,Fri Apr 05 16:08:37 +0000 2019,We have emailed the task details to all candid...,1,10,None
8,Fri Apr 05 04:05:11 +0000 2019,RT @rfpvjr: Our NAACL paper on polarization in...,16,0,None
9,Fri Apr 05 04:04:43 +0000 2019,RT @kdnuggets: Effective Transfer Learning For...,11,0,1
10,Wed Apr 03 18:31:53 +0000 2019,RT @stanfordnlp: What’s new in @Stanford CS224...,59,0,None
11,Wed Apr 03 17:04:32 +0000 2019,RT @DeepMindAI: Today we're releasing a large-...,848,0,None
12,Wed Apr 03 09:03:40 +0000 2019,RT @ylecun: Congratulations Jitendra Malik !\n...,16,0,None
13,Wed Apr 03 07:46:02 +0000 2019,RT @IIITDelhi: Another chance to take admissio...,4,0,None
14,Tue Apr 02 04:20:13 +0000 2019,Dear @midasIIITD internship candidates who hav...,1,8,None
15,Tue Apr 02 02:44:54 +0000 2019,Looking forward to your paper submission to @I...,1,5,None
16,Tue Apr 02 02:35:44 +0000 2019,RT @ngrams: Reproducibility in multimedia rese...,7,0,None
17,Mon Apr 01 06:53:08 +0000 2019,Online application for https://t.co/DJFDrQsHZP...,2,7,None
18,Sun Mar 31 10:21:24 +0000 2019,RT @ACMMM19: A final reminder of the Reproduci...,10,0,None
19,Fri Mar 29 19:43:24 +0000 2019,RT @isarth23: Thanks for the support and help ...,2,0,None
20,Fri Mar 29 17:16:40 +0000 2019,"Since SemEval-2019 will be held June 6-7, 2019...",1,9,None
21,Fri Mar 29 17:04:30 +0000 2019,+@aggarwal_kartik.\nCongrats! Wish you many mo...,0,2,None
22,Fri Mar 29 17:03:29 +0000 2019,RT @aggarwal_kartik: Our work (@midasIIITD ) a...,1,0,None
23,Fri Mar 29 17:02:24 +0000 2019,"Congratulations! @midasIIITD team, @isarth23 @...",1,9,None
24,Fri Mar 29 05:35:22 +0000 2019,@EEMLcommunity @radamihalcea too many deadline...,0,0,None
25,Thu Mar 28 16:55:01 +0000 2019,RT @stanfordnlp: CS224N Natural Language Proce...,715,0,None
26,Thu Mar 28 16:54:37 +0000 2019,RT @ylecun: Learn PyTorch by running on Google...,157,0,None
27,Wed Mar 27 16:09:09 +0000 2019,Dr. Vineeth N Balasubramanian will present a T...,1,4,None
28,Wed Mar 27 11:53:40 +0000 2019,RT @ylecun: I am extremely honored to be the r...,1546,0,None
29,Tue Mar 26 18:12:27 +0000 2019,Thanks to all shortlisted candidates for submi...,1,5,None
...,...,...,...,...,...
304,Thu Aug 09 10:17:53 +0000 2018,RT @kdnuggets: Ultimate Guide to Getting Start...,111,0,1
305,Thu Aug 09 05:59:57 +0000 2018,RT @TensorFlow: TensorFlow 1.10.0 has been rel...,265,0,None
306,Wed Aug 08 11:30:56 +0000 2018,@midasIIITD is looking for motivated IIITD MTe...,1,2,None
307,Wed Aug 08 05:53:48 +0000 2018,@IIITDelhi @ponguru @RatnRajiv The results of ...,1,3,1
308,Wed Aug 08 05:45:58 +0000 2018,RT @IIITDelhi: @midasIIITD has secured rank 1 ...,1,0,None
309,Tue Aug 07 07:16:33 +0000 2018,RT @kdnuggets: Comparison of Top 6 Python NLP ...,40,0,1
310,Tue Aug 07 02:05:12 +0000 2018,Check more details of the 20th IEEE Internatio...,1,1,None
311,Tue Aug 07 01:58:49 +0000 2018,MR2AMC@ISM 2018 will be organized by @RatnRaji...,1,1,None
312,Tue Aug 07 01:50:33 +0000 2018,"Our workshop proposal named, ""MR2AMC: Multimod...",1,1,None
313,Mon Aug 06 17:48:23 +0000 2018,@NUSComputing Congratulations Abdelhak and Pro...,0,0,None
314,Mon Aug 06 17:46:59 +0000 2018,RT @goodfellow_ian: One of the most anticipate...,103,0,1
315,Mon Aug 06 06:06:47 +0000 2018,@the_dhumketu Great to have you in @midasIIITD,0,0,None
316,Fri Aug 03 05:56:33 +0000 2018,Congratulation @soujanyaporia for being appoin...,1,6,None
317,Wed Aug 01 11:47:15 +0000 2018,@IIITDelhi @the_dhumketu Thanks team @midasIII...,1,5,1
318,Wed Aug 01 11:20:07 +0000 2018,RT @IIITDelhi: Congratulations @midasIIITD int...,4,0,None
319,Wed Aug 01 05:06:47 +0000 2018,RT @learning_pt: Profile of the 5 Indian under...,4,0,None
320,Tue Jul 31 12:11:52 +0000 2018,Have a look at the list of accepted papers in ...,0,1,None
321,Tue Jul 31 02:06:26 +0000 2018,RT @goodfellow_ian: https://t.co/hYiWI7ntyk Te...,264,0,None
322,Mon Jul 30 07:30:51 +0000 2018,RT @IIITDelhi: Congratulations Dr. @RatnRajiv ...,2,0,None
323,Sat Jul 28 11:07:11 +0000 2018,"RT @ylecun: Jitendra Malik, who directs FAIR-M...",57,0,None
324,Sat Jul 28 06:14:09 +0000 2018,RT @kdnuggets: .@Bloomberg launches free cours...,105,0,None
325,Sat Jul 28 06:13:48 +0000 2018,RT @TechAtBloomberg: Missed #PyLondinium18? Wa...,7,0,None
326,Sat Jul 28 04:08:21 +0000 2018,RT @IIITDelhi: We are delighted to announce th...,6,0,None
327,Fri Jul 27 06:46:44 +0000 2018,Get ready for the annual technical fest of @II...,2,3,None
328,Fri Jul 27 04:07:31 +0000 2018,Congratulations Dr. @RatnRajiv and team @midas...,2,8,None
329,Wed Jul 25 05:14:35 +0000 2018,Congratulations MIDAS @midasIIITD intern Prakh...,1,5,None
330,Tue Jul 24 10:33:23 +0000 2018,MIDAS@IIITD foundation. https://t.co/LKuzyBHzjm,1,2,None
331,Tue Jul 24 10:12:34 +0000 2018,It feels great to be the part of @IIITDelhi. h...,1,2,None
332,Tue Jul 24 09:46:26 +0000 2018,"Thank you, @toonzratn for designing the logo o...",1,4,1
333,Mon Jul 23 16:25:05 +0000 2018,We are on Facebook too. Like our page to get o...,1,3,None

In [23]:
d.columns

Index(['created_at', 'text', 'retweet_count', 'favorite_count', 'no_of_media'], dtype='object')